### ISSUE TITLE
hostname command on arch linux

### ISSUE THREAD

**Issue by ext8** [ipatch/theme-neolambda#4]
https://github.com/ipatch/theme-neolambda/blob/9b79e74624de9bbd3405e9feded51b77777b8be7/fish_prompt.fish#L52
on archlinux the way to get hostname is `hostnamectl hostname` , so on installing in archlinux it generates an error , i suggest you check if hostname command exists before using it on install

```fish
 set -g __fish_prompt_hostname $blue(hostnamectl hostname|cut -d . -f 1)(set_color normal) 
```

**Comment by ipatch** [comment]
thanks for pointing this out. 👍

i'll setup a "test" user on my archbox and see if i can come up with a more graceful error message or as you state a better check to see if the `hostname` cmd is installed.

**Comment by Kiramily** [comment]
fish has a built-in [hostname](https://fishshell.com/docs/current/language.html?highlight=hostname#envvar-hostname) variable

Replacing ``hostname|cut -d . -f 1`` with ```echo $hostname``` fixed the issue for me

**Comment by ipatch** [comment]
> fish has a built-in [hostname](https://fishshell.com/docs/current/language.html?highlight=hostname#envvar-hostname) variable
> 
> Replacing `hostname|cut -d . -f 1` with `echo $hostname` fixed the issue for me

that's awesome, thanks for sharing.

**Comment by ipatch** [comment]
forgive my tardiness finally spending some to address this issue. i see what y'all are talking about. i just spun up am archlinux docker container, and am seeing the below output after installing my theme,

```
⋊> / omf install neolambda                                                                                                                     18:48:14
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package neolambda
✔ neolambda successfully installed.
fish: Unknown command: hostname
~/.config/fish/functions/fish_prompt.fish (line 1):
hostname|cut -d . -f 1
^
in command substitution
        called on line 34 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution
~/.config/fish/functions/fish_prompt.fish (line 34): Unknown command
    set -g __fish_prompt_hostname $orange(hostname|cut -d . -f 1)(set_color normal)
                                         ^
in function 'fish_prompt'
in command substitution
╭─root at
╰─λ           
```

i'll try and get this resolved 🤞

**Comment by ipatch** [comment]
again kudos 🥳 for `echo $hostname` that seems to run a tad quicker than the upstream `uname -n`

```
╭─capin ssh archmbp in /home/capin
╰─λ time echo $hostname                                                                                                                      0 (0.000s)
archmbp

________________________________________________________
Executed in   47.00 micros    fish           external
   usr time   39.00 micros   39.00 micros    0.00 micros
   sys time   11.00 micros   11.00 micros    0.00 micros

╭─capin ssh archmbp in /home/capin
╰─λ time uname -n                                                                                                                            0 (0.002s)
archmbp

________________________________________________________
Executed in    1.36 millis    fish           external
   usr time    1.37 millis  293.00 micros    1.08 millis
   sys time    0.08 millis   76.00 micros    0.00 millis

```

**Comment by ipatch** [comment]
#9
