### ISSUE TITLE
#macos macos hostname now shows `example.local` on macos

### ISSUE THREAD

**Issue by ipatch** [ipatch/theme-neolambda#7]
after updating my theme with #6 my prompt now looks like the below

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/613805/167938838-6800e07b-d5a5-4c59-94bf-e4389674093b.png">

probably easy enough to use the `cut` cmd to trim out the `.local` portion of the hostname

**Comment by Kiramily** [comment]
I completely missed [prompt_hostname](https://fishshell.com/docs/current/cmds/prompt_hostname.html) in the Documentation but this command should fix this.

I'll open a PR with the fix.

**Comment by ipatch** [comment]
thank you. 🙏  #9
